UTILS = utils/array_io.cpp \
		utils/partial_sum.cpp

FLAGS = -fopenmp -Wall -Wextra -Werror -pedantic

1:
	clang++ $(FLAGS) exercise_1.cpp $(UTILS) -o exercise_1

2:
	clang++ $(FLAGS) exercise_2.cpp $(UTILS) -o exercise_2

3:
	clang++ $(FLAGS) exercise_3.cpp $(UTILS) -o exercise_3

4:
	clang++ $(FLAGS) exercise_4.cpp $(UTILS) -o exercise_4

clean:
	rm -f exercise_1 exercise_2 exercise_3 exercise_4
